In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [14]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)

epsilon = np.random.normal(0,10,100)

In [15]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [16]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [17]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.961
Model:                            OLS   Adj. R-squared:                  0.959
Method:                 Least Squares   F-statistic:                     383.5
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           2.71e-63
Time:                        20:21:49   Log-Likelihood:                -371.06
No. Observations:                 100   AIC:                             756.1
Df Residuals:                      93   BIC:                             774.4
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -33.7984      6.181     -5.468      0.000     -46.073     -21.523
X1             1.3022      0.122     10.656      0.000       1.059       1.545
X2             1.6029      0.052     30.982      0.000       1.500       1.706
X3             1.1861      0.092     12.932      0.000       1.004       1.368
X4             0.5878      0.110      5.331      0.000       0.369       0.807
X5            -2.0370      0.058    -34.891      0.000      -2.153      -1.921
X6            -0.7873      0.088     -8.947      0.000      -0.962      -0.613
==============================================================================
Omnibus:                        0.275   Durbin-Watson:                   1.688
Prob(Omnibus):                  0.872   Jarque-Bera (JB):                0.101
Skew:                          -0.075   Prob(JB):                        0.951
Kurtosis:                       3.041   Cond. No.                         426.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

We try lasso

In [18]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [19]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [20]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.963
Model:                            OLS   Adj. R-squared:                  0.958
Method:                 Least Squares   F-statistic:                     189.4
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           6.72e-57
Time:                        20:21:49   Log-Likelihood:                -368.45
No. Observations:                 100   AIC:                             762.9
Df Residuals:                      87   BIC:                             796.8
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -38.7499      9.434     -4.107      0.000     -57.501     -19.999
X1             1.3323      0.126     10.604      0.000       1.083       1.582
X2             1.6063      0.055     29.292      0.000       1.497       1.715
X3             1.2272      0.096     12.782      0.000       1.036       1.418
X4             0.6049      0.118      5.128      0.000       0.370       0.839
X5            -2.0282      0.060    -33.560      0.000      -2.148      -1.908
X6            -0.7740      0.091     -8.512      0.000      -0.955      -0.593
X7            -0.0071      0.122     -0.059      0.953      -0.249       0.235
X8             0.0143      0.051      0.283      0.778      -0.087       0.115
X9             0.0339      0.101      0.334      0.739      -0.168       0.235
X10            0.1028      0.122      0.841      0.403      -0.140       0.346
X11           -0.0882      0.052     -1.680      0.097      -0.193       0.016
X12           -0.0727      0.090     -0.807      0.422      -0.252       0.106
==============================================================================
Omnibus:                        1.287   Durbin-Watson:                   1.695
Prob(Omnibus):                  0.526   Jarque-Bera (JB):                0.771
Skew:                          -0.074   Prob(JB):                        0.680
Kurtosis:                       3.404   Cond. No.                         905.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [21]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account
# alpha: higher, higher regulation and the model coefficient more likely to be zero 
X_ext = X_ext.drop(columns=['Constant'])#drop X0 = 1 
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.31588069,  1.60178267,  1.21494734,  0.59086202, -2.02534176,
       -0.76590611, -0.        ,  0.01243348,  0.02448482,  0.09134539,
       -0.08396009, -0.06455548])

In [22]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.15951704,  1.56025929,  1.10882935,  0.4529044 , -1.99283005,
       -0.68092178, -0.        ,  0.        ,  0.        ,  0.        ,
       -0.03978697, -0.        ])

In [23]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.33009983,  1.60570591,  1.22599838,  0.60378304, -2.02735831,
       -0.77294528, -0.00753215,  0.01426734,  0.03420894,  0.10278205,
       -0.0878669 , -0.07275878])

In [24]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.496245  ,  1.20187375,  0.60912114,  0.19699036, -1.49509289,
       -0.30349789, -0.07353183, -0.04136381,  0.11303685,  0.05231849,
        0.02629642, -0.10106694])